# Generated by Django 4.2.6 on 2023-10-25 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_manager', models.CharField(max_length=50)),
                ('telegram_nickname', models.CharField(max_length=50)),
                ('telegram_chat_id', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=20)),
                ('timeslot', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('telegram_nickname', models.CharField(max_length=50)),
                ('telegram_chat_id', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('requsted_period', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('brief', models.CharField(max_length=20)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots_student', to='admin_panel.student')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots_period', to='admin_panel.pm')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots_project_manager', to='admin_panel.pm')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots_timeslot', to='admin_panel.pm')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_timeslot', to='admin_panel.timeslot'),
        ),
    ]
