# Generated by Django 4.2.6 on 2023-10-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_manager', models.CharField(max_length=50, unique=True)),
                ('telegram_nickname', models.CharField(max_length=50, unique=True)),
                ('telegram_chat_id', models.CharField(max_length=50, unique=True)),
                ('period', models.CharField(max_length=20)),
                ('timeslot', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_chat_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='requsted_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_period', to='admin_panel.projectmanager'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots_period', to='admin_panel.projectmanager'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots_project_manager', to='admin_panel.projectmanager'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots_timeslot', to='admin_panel.projectmanager'),
        ),
        migrations.DeleteModel(
            name='PM',
        ),
    ]
