# Generated by Django 4.2.6 on 2023-10-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_team_rename_project_manager_projectmanager_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='requsted_period',
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(default=34234, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='admin_panel.team'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='team',
            name='students',
        ),
        migrations.AddField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='admin_panel.student'),
        ),
    ]
