# Generated by Django 4.2.6 on 2023-10-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_alter_team_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
