# Generated by Django 4.2.6 on 2023-10-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_alter_projectmanager_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_time',
            field=models.DateTimeField(),
        ),
    ]
