# Generated by Django 4.0.5 on 2023-10-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_alter_team_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_team', to='admin_panel.student'),
        ),
    ]
