# Generated by Django 4.0.5 on 2023-10-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_alter_team_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='missing', max_length=50),
        ),
    ]
