# Generated by Django 4.0.5 on 2023-10-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_student_registration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='student_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_panel.team'),
        ),
    ]
