# Generated by Django 4.0.5 on 2023-10-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_remove_student_team_remove_team_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_team',
        ),
        migrations.CreateModel(
            name='StudentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_team', to='admin_panel.student')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_panel.team')),
            ],
        ),
    ]
