# Generated by Django 4.0.5 on 2023-10-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_remove_student_student_team_studentteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteam',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_team', to='admin_panel.student'),
        ),
    ]
