# Generated by Django 4.2.6 on 2023-10-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_projectmanager_rename_full_name_student_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('students', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('brief', models.CharField(max_length=20)),
                ('trello_board_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='projectmanager',
            old_name='project_manager',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='student',
            name='telegram_nickname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='student',
            name='requsted_period',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AddField(
            model_name='team',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots_project_manager', to='admin_panel.projectmanager', verbose_name='project_manager'),
        ),
    ]
